package com.exampl.model;

public class TStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    private Double id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stuName
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    private String stuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.age
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    private Double age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.sex
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.gradeName
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    private String gradename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    public Double getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    public void setId(Double id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stuName
     *
     * @return the value of t_student.stuName
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stuName
     *
     * @param stuname the value for t_student.stuName
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.age
     *
     * @return the value of t_student.age
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    public Double getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.age
     *
     * @param age the value for t_student.age
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    public void setAge(Double age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.sex
     *
     * @return the value of t_student.sex
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.sex
     *
     * @param sex the value for t_student.sex
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.gradeName
     *
     * @return the value of t_student.gradeName
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    public String getGradename() {
        return gradename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.gradeName
     *
     * @param gradename the value for t_student.gradeName
     *
     * @mbg.generated Fri May 11 22:21:54 CST 2018
     */
    public void setGradename(String gradename) {
        this.gradename = gradename == null ? null : gradename.trim();
    }
}